name: Matrix using
on: workflow_dispatch
#  push:
#    branches:
#      - main
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - node-version: 18.x
            operating-system: ubuntu-latest
        exclude:
          - node-version: 24.x
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
